### ISSUE TITLE
The 'Event' name 

### ISSUE THREAD

**Issue by Tangdixi** [onmyway133/Github.swift#2]
I was try to do something like this in my **viewModel**:  

``` Swift
struct UserEventModel {

  let events: Observable<[Event]>

}
```

It seems the name [Event](https://github.com/onmyway133/Github.swift/blob/master/Sources/Classes/Event/Event.swift) conflict with the [Event](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Event.swift) in RxSwift.  

: (

**Comment by onmyway133** [comment]
@Tangdixi Swift has namespace, so I think `GithubSwift.Event` will work

**Comment by Tangdixi** [comment]
@onmyway133 Thx for your help ~

**Comment by onmyway133** [comment]
@Tangdixi you're welcome 🎉
